import type { AuthoringModel } from './models';

/**
 * A guide for each authoring model, written for an assistant that has the model's JSON Schema in
 * front of it: what the model is for, how its parts fit, what each kind is for, and what goes
 * wrong. The meanings come from the model files' comments and the editor's own descriptions
 * (`scripts/describe.ts`, `combat/describe.ts`). A test fails when a model gains a kind these guides
 * do not mention, so adding one means adding its line here.
 */

const lines = (...parts: string[]): string => parts.join('\n');

const SCENE = lines(
  '## What it is',
  'A scene is one thing that happens in a quest: when `trigger` happens to `owner`, and only if every one of `gates` holds, the `steps` run in order. Scenes are stored on the quest and compiled into the game server\'s scripts when a patch is exported. Write the scene; never write script rows.',
  '',
  '## How the parts fit',
  '- `owner` is who the scene runs on, by `entry` for an NPC or object. Use the quest giver for acceptance and hand-in scenes, and the target for kill or use scenes.',
  '- `waitMs` on a step is a pause before it runs. Text can use `$N` for the player\'s name.',
  '- A step that needs "the player" (credit, give or take an item, cast on the player, start an escort) only works when a player sets the scene off, which is every trigger except `signal`, `waypointReached` and `summoned`.',
  '- `name` is a short label for the author. `id` looks like `s1`, `s2` (the letter s and a number); leave it out and the next free one is chosen.',
  '- `say`, `moveTo`, `startEscort`, `npcFlags` and `faction` only work on an NPC owner. An area owner cannot wait between steps. `eventCredit` only completes a quest that is set to complete from a script event.',
  '',
  '## Kinds',
  '### Owners',
  '- `creature` — an NPC, by `entry`.',
  '- `gameobject` — an object, by `entry`.',
  '- `areatrigger` — an invisible area, by `id` and an `area` (map, x, y, z, radius).',
  '### Triggers',
  '- `questAccepted` — a player takes the quest from the owner.',
  '- `questHandedIn` — a player hands the quest in to the owner.',
  '- `spellHit` — a spell (`spellId`, 0 for any) or quest item is used on the owner.',
  '- `dies` — the owner (an NPC) dies; the killer is the player.',
  '- `talkedTo` — a player talks to or uses the owner.',
  '- `gossipOption` — adds a talk option (`text`) to the owner (an NPC); `greeting` is the line above the options.',
  '- `playerNear` — a player comes within `range` yards of the owner (an NPC).',
  '- `enterArea` — a player walks into the area (owner `areatrigger`).',
  '- `signal` — another scene told this owner `signal` (an integer both sides agree on).',
  '- `waypointReached` — an escort scene (`escortSceneId`) reaches `point`.',
  '- `summoned` — a scene spawned the owner.',
  '### Gates',
  '- `quest` — a quest (`questId`, 0 for this one) is in a `state`: `inLog`, `objectivesDone`, `handedIn` or `neverTaken`; `negate` flips it.',
  '- `item` — the player has (or, negated, lacks) `count` of `item`.',
  '- `team` — the player is `alliance` or `horde`.',
  '### Steps',
  '- `say` — the owner speaks `text` as `say`, `yell` or `emote`.',
  '- `emote` — play an emote animation by number.',
  '- `credit` — count objective 1 to 4 for the player (or `group`).',
  '- `eventCredit` — complete the quest\'s event objective.',
  '- `failQuest` — fail the quest for the player.',
  '- `castOnPlayer` — cast `spellId` on the player.',
  '- `castOnSelf` — the owner casts `spellId` on itself.',
  '- `giveItem` — give the player `count` of `item`.',
  '- `takeItem` — take `count` of `item` from the player.',
  '- `spawnNpc` — spawn an NPC `entry` at `at` (x, y, z, o), gone after `despawnAfterS` seconds (0 = stays), optionally attacking the player.',
  '- `spawnObject` — spawn an object `entry` at `at`.',
  '- `despawn` — remove the owner (`entry` 0) or the nearest NPC `entry` within `range`.',
  '- `moveTo` — the owner walks to `at`.',
  '- `startEscort` — the owner walks `points` in order (`run` or walk); pair it with a `waypointReached` scene.',
  '- `npcFlags` — turn the owner\'s quest-giver and gossip on, off or keep.',
  '- `faction` — change the owner\'s faction (0 restores it).',
  '- `objectState` — open or close an object.',
  '- `signal` — tell the NPC or object `entry` near the owner a `signal` number, to start another scene.',
  '- `closeGossip` — close the talk window.',
  '',
  '## Common mistakes',
  '- Leaving an `entry` or `spellId` at 0 where one is needed: the editor lists it as unfinished.',
  '- A trigger the owner cannot carry (`dies` on an object, `enterArea` on an NPC).',
  '- A `credit` step in a scene with no player, or credit for an objective the quest does not have.',
  '- Sending a `signal` nobody listens for, or listening for one nobody sends.',
  '',
  '## What the editor checks',
  'Every write returns the editor\'s issues for the quest. Errors stop an export: `SCENE_STEP_INCOMPLETE` (a step is missing something it needs), `SCENE_WRONG_OWNER` (the owner cannot carry that trigger or step), `SCENE_NO_PLAYER` (a step acts on the player but no player sets the trigger off), `SCENE_CREDIT_EMPTY` (credit for an objective that is not an NPC objective), `SCENE_NO_ESCORT` (the escort a `waypointReached` scene waits for is gone), `SCENE_AREA_WAIT` (an area scene waits) and `SCENE_NO_OWNER`. Warnings: `SCENE_NO_STEPS`, `SCENE_EVENT_FLAG` (the quest will not complete from a script event) and `SCENE_ACCEPT_NOT_GIVER` (the owner does not offer or take back the quest). Fix what it reports.',
);

const FIGHT = lines(
  '## What it is',
  'A fight belongs to a new NPC and describes how it behaves in combat in three parts: `abilities` it casts on timers, `reactions` to things that happen, and optional `phases` that stay out of play until a reaction moves the fight on. It is compiled into the game server\'s scripts when a patch is exported.',
  '',
  '## How the parts fit',
  '- An ability casts `spellId` on a `target` (`victim`, `secondThreat`, `random`, `randomNotTank`, `self`): first after `firstMinS`–`firstMaxS` seconds, then every `repeatMinS`–`repeatMaxS` (both 0 = once).',
  '- A new NPC is friendly to everyone (faction 35) and never enters combat. Give an NPC that should fight a hostile `faction` such as 14, and a model.',
  '- `keepDistance` makes it cast from range (only one ability may have it); `skipIfAuraPresent` skips the cast while the target still has the effect. A `hurtFriend` target only works in a `friendHealthBelow` reaction. `phases` on `aggro`, `death` and `evade` reactions are ignored: they happen in every phase.',
  '- `phases` is a list of names. With none, everything is always on. With some, the fight starts in phase 1, and an ability or reaction with `phases: [2]` only runs in phase 2 (an empty list = every phase).',
  '- A reaction is `when` something happens, run `steps` in order. Spells are numbers from the spell list; use 0 only as a placeholder to finish later.',
  '',
  '## Kinds',
  '### Reactions (when)',
  '- `aggro` — it enters combat.',
  '- `healthBelow` — it drops below `pct` percent health (1 to 99).',
  '- `friendHealthBelow` — a friend within `range` yards drops below `pct` percent.',
  '- `addDies` — one of its adds dies (`entry` 0 = any).',
  '- `kill` — it kills a player.',
  '- `death` — it dies.',
  '- `evade` — it gives up and resets.',
  '### Steps',
  '- `say` — speak `text` as `say`, `yell` or `emote`.',
  '- `emote` — play an emote animation.',
  '- `cast` — cast `spellId` on a `target` (the ability targets, or `hurtFriend`).',
  '- `summonAdds` — summon `count` of NPC `entry` around itself or at a point; `attack` sends them at the target.',
  '- `despawnAdds` — remove its adds (`entry` 0 = all).',
  '- `goToPhase` — move the fight to `phase`.',
  '- `flee` — run away calling for help.',
  '- `callForHelp` — call allies within `radius` yards.',
  '- `holdAtHealth` — stop taking damage at `pct` percent; pair with `surrender`.',
  '- `surrender` — stop fighting and turn friendly (it turns hostile again after about two minutes).',
  '- `credit` — give quest credit for objective 1 to 4 (`quest` names the quest, 0 = none yet).',
  '',
  '## Common mistakes',
  '- Spell 0 left in an ability or `cast` step.',
  '- A reaction or ability in a phase the fight does not have (`phases` lists fewer names than the number used).',
  '- `healthBelow` at 0 or 100.',
  '- `summonAdds` with entry 0, or credit for an objective the quest lacks.',
  '',
  '## What the editor checks',
  'Writing a fight returns the editor\'s issues for that NPC. Errors stop an export: `FIGHT_NO_SPELL`, `FIGHT_TIMING` (times out of order), `FIGHT_HEALTH_PCT` (not 1 to 99), `FIGHT_HURT_FRIEND`, `FIGHT_NO_ADD`, `FIGHT_PHASE_MISSING`, `FIGHT_TWO_MAIN_SPELLS` and the credit checks (`FIGHT_CREDIT_NO_QUEST`, `FIGHT_CREDIT_QUEST_MISSING`, `FIGHT_CREDIT_EMPTY`). Warnings: `FIGHT_UNKNOWN_SPELL` (not in the server\'s spell list), `FIGHT_PHASE_UNREACHED`, `FIGHT_EMPTY_REACTION` and `FIGHT_TOO_FAST` (repeats faster than every 2 seconds). The NPC also needs a model, a name and levels (see the npc guide).',
);

const PATROL = lines(
  '## What it is',
  'A patrol belongs to one spawn of a new NPC. The NPC walks `points` in order, pauses, then loops back to where it started and walks again. It is written as a waypoint path when a patch is exported.',
  '',
  '## How the parts fit',
  '- `pathId` is the waypoint path id. Do not set it: `set_npc_patrol` chooses it, and keeps the spawn\'s own when you set its patrol again.',
  '- `startPace` is `walk` or `run`; a point can change it from there on with `paceFromHere`.',
  '- Each point has `x`, `y`, `z` (world yards: X north, Y west), `waitSecs` (the pause there), and `facing` in radians (0 faces north, growing toward west) or null to keep the way it walked in.',
  '- `actions` happen at the point, each `afterSecs` seconds after arriving.',
  '',
  '## Kinds',
  '### Point actions',
  '- `say` — speak one of `lines` (picked at random) with the given `chance` percent.',
  '- `emote` — play the emote number once.',
  '- `pose` — hold an emote state (kneel, mine…) while it waits, undone before it walks on.',
  '- `cast` — cast `spell`.',
  '- `sound` — play `sound`.',
  '- `mount` — mount creature `creature`.',
  '- `dismount` — dismount.',
  '- `useObject` — use the object spawn `guid` of `entry`.',
  '',
  '## Common mistakes',
  '- A patrol with fewer than two points walks nowhere.',
  '- Points on different maps or far from the spawn: keep the route near it and on the ground.',
  '- A point action with nothing chosen (an emote, spell or sound left empty): the editor reports `PATROL_UNPICKED`.',
  '',
  '## What the editor checks',
  'The editor reports a point action with nothing chosen as `PATROL_UNPICKED`, in the NPC\'s issues. Routes of existing database NPCs are edited with `set_route`, not here.',
);

const LOOT = lines(
  '## What it is',
  'Loot is the list of items a new NPC drops when killed or a new object gives when opened. It replaces the whole list each time it is written.',
  '',
  '## How the parts fit',
  'Each row is independent: when the NPC dies, every row rolls its own `chance`.',
  '',
  '## Fields',
  '- `item` — the item entry (an existing one, or a new one from `new_entity`).',
  '- `chance` — percent, 0 to 100; 100 always drops.',
  '- `min`, `max` — how many drop (a count between them).',
  '- `questOnly` — drops only for a player who needs it for a quest.',
  '',
  '## Common mistakes',
  '- An `item` of 0 (`LOOT_NO_ITEM`), a `chance` outside 0 to 100 (`LOOT_CHANCE`), or `min` below 1 or above `max` (`LOOT_COUNT`): errors that stop an export.',
  '- A typo in an item number. The editor does not check that an item exists: confirm it with `check_ids` and `lookup_names`.',
  '- The same item twice in one list; the loot table is keyed by item, so list each item once.',
  '- Many 100% rows on a common NPC: it floods the economy.',
  '',
  '## What the editor checks',
  'The editor reports `LOOT_NO_ITEM`, `LOOT_CHANCE`, `LOOT_COUNT`, `LOOT_QUEST_ITEM` (an item a quest asks for belongs in that quest\'s Objectives, not here) and `LOOT_EMPTY_CHEST` (a chest with nothing in it). It does not check that an item exists. An existing database NPC or object may have its loot locked because other things share the table; make a new NPC instead.',
);

const NPC = lines(
  '## What it is',
  'A new NPC for the project: a creature template with its look, levels, faction and role, any number of spawns (where it stands), its loot and its fight. It is written as database rows when a patch is exported.',
  '',
  '## How the parts fit',
  'Make it with `new_entity`, then use `set_loot`, `set_npc_fight` and `set_npc_patrol` for the nested models. To place it, add entries to its `spawns` with `upsert_entity` (a spawn has `guid`, `map`, `x`, `y`, `z`, `o`, `respawnSecs`, `wander`, `patrol`, `rotation`, `events`), taking each `guid` from `allocate_ids` with kind `creatureSpawn`. `add_spawn` places only NPCs that already exist in the database.',
  '',
  '## Fields',
  '- `entry` — its id; chosen for you by `new_entity`. Do not change it.',
  '- `name`, `subname` — the name and the title under it ("Innkeeper").',
  '- `minLevel`, `maxLevel` — its level range; the minimum is at least 1 and not above the maximum.',
  '- `faction` — a faction template id: 35 friendly to all, 14 hostile to all, 11 Stormwind, 85 Orgrimmar, 7 monster. A new NPC starts at 35 and never fights; give one that should fight a hostile faction such as 14.',
  '- `displayId` — its model; 0 means none yet and blocks an export. Copy one from an existing NPC with `entity_template`.',
  '- `scale`, `healthModifier`, `damageModifier` — size and strength multipliers (1 = normal).',
  '- `rank` — `normal`, `elite`, `rareElite`, `boss` or `rare`.',
  '- `type` — `beast`, `dragonkin`, `demon`, `elemental`, `giant`, `undead`, `humanoid`, `critter`, `mechanical` or `none`.',
  '- `questGiver`, `gossip` — whether it offers quests and has a talk window.',
  '- `spawns` — where it stands: `guid`, `map`, `x`, `y`, `z`, `o` (facing in radians), `respawnSecs`, `wander`, `patrol`.',
  '- `equipment` — items in `mainHand`, `offHand` and `ranged`.',
  '- `origin` — `new`, or `existing` for a database NPC the project took over; an existing one may be `locked` for `fight` or `loot`.',
  '',
  '## Common mistakes',
  '- No `displayId`, no name, or `minLevel` above `maxLevel`: the editor reports each as an error.',
  '- A `questGiver` the player cannot see (see `seenBy`).',
  '- Reusing an entry: use `new_entity`, which picks a free one.',
  '',
  '## What the editor checks',
  'Writing an NPC returns the editor\'s issues for it. Errors stop an export: `ENTITY_NO_NAME`, `ENTITY_NO_MODEL` and `ENTITY_LEVELS`. Warnings: `ENTITY_NO_SPAWN` (nothing places it in the world), `ENTITY_SPAWN_ORIGIN` (a spawn is still at 0, 0, 0), `ENTITY_GHOST_GIVER` (it gives quests but only the dead see it), `ENTITY_WEAPON` (a held item that is missing or not held in a hand) and `ENTITY_TAKEN` (the entry already holds something in the database, which it would replace). Its fight and patrols add the `FIGHT_` and `PATROL_UNPICKED` checks.',
);

const OBJECT = lines(
  '## What it is',
  'A new object for the project: a chest, a readable book or sign, a door or switch, or a generic thing in the world, with spawns and, for chests, loot. It is written as database rows when a patch is exported.',
  '',
  '## How the parts fit',
  'Make it with `new_entity`, set its `type` and look, and use `set_loot` for a chest. Readable ones have `pages` of text. To place it, add entries to its `spawns` with `upsert_entity`, taking each `guid` from `allocate_ids` with kind `gameobjectSpawn`. `add_spawn` places only objects that already exist in the database.',
  '',
  '## Fields',
  '- `entry` — its id; chosen for you. Do not change it.',
  '- `name` — what the player sees.',
  '- `type` — `questGiver`, `chest`, `generic`, `text` (a readable page), or `goober` (something you click).',
  '- `displayId`, `size` — its model and scale (1 = normal).',
  '- `spawns` — where it stands: `guid`, `map`, `x`, `y`, `z`, `o`, `rotation` (a quaternion x, y, z, w; copy it from a neighbour with `area_overview`).',
  '- `pages` — text pages for a `text` object.',
  '- `onlyDuringQuest` — a quest id the player must have in the log to use or loot it, or null.',
  '- `loot` — what a chest gives (see the loot guide).',
  '',
  '## Common mistakes',
  '- No model (`displayId` 0) or no name.',
  '- A readable object with no pages.',
  '- A `rotation` of null (the default for a new object) turns it by `o` alone. To match a neighbour, copy its `rotation` from `area_overview`; an all-zero stored rotation reads as upright facing north.',
  '',
  '## What the editor checks',
  'Writing an object returns the editor\'s issues for it: `ENTITY_NO_NAME`, `ENTITY_NO_MODEL`, `ENTITY_NO_SPAWN`, `ENTITY_NO_PAGES` for a readable object without pages, and `LOOT_EMPTY_CHEST` for a chest with nothing in it, plus the loot checks.',
);

const ITEM = lines(
  '## What it is',
  'A new item for the project: a weapon, armour, trinket or quest item, with its quality, level, stats and effects. It is written as an `item_template` row when a patch is exported.',
  '',
  '## How the parts fit',
  'Make it with `new_entity`, then set `fields`. A quest item (`itemClass` 12, `bonding` `quest`) is the default. For a weapon or armour set `itemClass`, `subclass`, `inventoryType` and the stats. Name it in `check_names` first.',
  '',
  '## Fields',
  '- `entry` — its id; chosen for you. Do not change it.',
  '- `name`, `description` — the title and the flavour text.',
  '- `quality` — `poor`, `common`, `uncommon`, `rare`, `epic`, `legendary`, `artifact` or `heirloom`.',
  '- `itemClass`, `subclass`, `inventoryType` — what it is: class 2 weapon, 4 armour, 12 quest; the inventory type is the slot (13 one-hand, 17 two-hand, 14 shield).',
  '- `displayId` — its icon and model; copy one from an existing item with `entity_template`.',
  '- `itemLevel`, `requiredLevel` — its power and the level needed to use it.',
  '- `stackable`, `maxCount` — stack size and how many a player may own.',
  '- `bonding` — `none`, `pickup`, `equip`, `use` or `quest`.',
  '- `buyPrice`, `sellPrice` — in copper.',
  '- `startsQuest` — a quest id this item begins when used, or 0.',
  '- `armor`, `damage` (min, max, school), `delayMs` — armour value and weapon damage and speed.',
  '- `stats` — up to 10 `{ type, value }` pairs, `type` being the game\'s stat number.',
  '- `spells` — up to 5 effects: `spell`, `trigger` (when it fires), `charges`, `cooldownMs`.',
  '- `advanced` — any other `item_template` column, as text.',
  '',
  '## Common mistakes',
  '- A weapon with no `damage` or `delayMs`, or armour with `armor` 0.',
  '- A `legendary` item at a low `itemLevel`.',
  '- A `startsQuest` for a quest that does not exist.',
  '',
  '## What the editor checks',
  'Writing an item returns the editor\'s issues for it, such as `ITEM_NO_NAME`, `ITEM_NO_LOOK` (no look chosen), `ITEM_LEVELS`, `ITEM_STACK`, `ITEM_STARTS_UNKNOWN` (the quest it starts does not exist) and `ENTITY_TAKEN` (the entry already holds something in the database). A weapon an NPC cannot hold is reported on that NPC as `ENTITY_WEAPON`.',
);

const GUIDES: Record<AuthoringModel, string> = {
  scene: SCENE,
  fight: FIGHT,
  patrol: PATROL,
  loot: LOOT,
  npc: NPC,
  object: OBJECT,
  item: ITEM,
};

/** The guide for an authoring model: markdown, at most 6000 characters. */
export const guideOf = (model: AuthoringModel): string => GUIDES[model];
