/**
 * Race, class, quest-sort and emote lookup data for the identity and story controls.
 *
 * The bit values and IDs below are pinned to the reference fork's server source
 * (`E:\Repositories\azerothcore-wotlk-coa`, read-only), not to stock AzerothCore, per the Task 7
 * ledger ruling. Read directly from the fork rather than assumed from memory:
 * - `RACES` / `ALLIANCE_MASK` / `HORDE_MASK`: `enum Races` in `src/server/shared/SharedDefines.h`.
 *   The fork's race IDs (Human=1 .. Draenei=11, with the historical Goblin=9 gap) are unchanged
 *   from stock, so the bit values (`1 << (raceId - 1)`) match the brief's pinned list exactly.
 * - `CLASSES`: `enum Classes` in `src/server/shared/SharedDefines.h`. The fork keeps the original
 *   10 playable classes (Warrior=1 .. Warlock=9, Druid=11) at their stock bit values, then reserves
 *   class ID 10 (`CLASS_HERO`, commented out - Ascension's classless/free-pick shell) and adds 22
 *   more custom classes (Barbarian=12 through Spirit Mage=32; `MAX_CLASSES` is 33). Only the
 *   original 10 are listed here: class IDs above 30 would need bit 1<<30/1<<31, and JS's 32-bit
 *   signed bitwise operators cannot represent those bits safely for mask math, so extending this
 *   list to the fork's full 32 classes is out of scope for the mask control (see task report).
 * - Quest log categories (`enum QuestSort`) live in `src/core/game/quest-sorts.ts`, beside the zones
 *   they are searched with.
 * - `EMOTES`: `enum Emote` in `src/server/shared/SharedDefines.h` (search anchor: `EMOTE_ONESHOT_TALK`).
 *   All 174 named values are listed, labelled from their constant name with a "(one-shot)"/"(state)"
 *   suffix to disambiguate pairs like `EMOTE_ONESHOT_DANCE` vs `EMOTE_STATE_DANCE` that would
 *   otherwise share a label.
 */

export const RACES: { bit: number; label: string }[] = [
  { bit: 1, label: 'Human' },
  { bit: 2, label: 'Orc' },
  { bit: 4, label: 'Dwarf' },
  { bit: 8, label: 'Night Elf' },
  { bit: 16, label: 'Undead' },
  { bit: 32, label: 'Tauren' },
  { bit: 64, label: 'Gnome' },
  { bit: 128, label: 'Troll' },
  { bit: 512, label: 'Blood Elf' },
  { bit: 1024, label: 'Draenei' },
];

/** Human, Dwarf, Night Elf, Gnome, Draenei. */
export const ALLIANCE_MASK = 1 | 4 | 8 | 64 | 1024;

/** Orc, Undead, Tauren, Troll, Blood Elf. */
export const HORDE_MASK = 2 | 16 | 32 | 128 | 512;

export const CLASSES: { bit: number; label: string }[] = [
  { bit: 1, label: 'Warrior' },
  { bit: 2, label: 'Paladin' },
  { bit: 4, label: 'Hunter' },
  { bit: 8, label: 'Rogue' },
  { bit: 16, label: 'Priest' },
  { bit: 32, label: 'Death Knight' },
  { bit: 64, label: 'Shaman' },
  { bit: 128, label: 'Mage' },
  { bit: 256, label: 'Warlock' },
  { bit: 1024, label: 'Druid' },
];

export const EMOTES: { value: number; label: string }[] = [
  { value: 1, label: 'Talk (one-shot)' },
  { value: 2, label: 'Bow (one-shot)' },
  { value: 3, label: 'Wave (one-shot)' },
  { value: 4, label: 'Cheer (one-shot)' },
  { value: 5, label: 'Exclamation (one-shot)' },
  { value: 6, label: 'Question (one-shot)' },
  { value: 7, label: 'Eat (one-shot)' },
  { value: 10, label: 'Dance (state)' },
  { value: 11, label: 'Laugh (one-shot)' },
  { value: 12, label: 'Sleep (state)' },
  { value: 13, label: 'Sit (state)' },
  { value: 14, label: 'Rude (one-shot)' },
  { value: 15, label: 'Roar (one-shot)' },
  { value: 16, label: 'Kneel (one-shot)' },
  { value: 17, label: 'Kiss (one-shot)' },
  { value: 18, label: 'Cry (one-shot)' },
  { value: 19, label: 'Chicken (one-shot)' },
  { value: 20, label: 'Beg (one-shot)' },
  { value: 21, label: 'Applaud (one-shot)' },
  { value: 22, label: 'Shout (one-shot)' },
  { value: 23, label: 'Flex (one-shot)' },
  { value: 24, label: 'Shy (one-shot)' },
  { value: 25, label: 'Point (one-shot)' },
  { value: 26, label: 'Stand (state)' },
  { value: 27, label: 'Ready Unarmed (state)' },
  { value: 28, label: 'Work Sheathed (state)' },
  { value: 29, label: 'Point (state)' },
  { value: 30, label: 'None (state)' },
  { value: 33, label: 'Wound (one-shot)' },
  { value: 34, label: 'Wound Critical (one-shot)' },
  { value: 35, label: 'Attack Unarmed (one-shot)' },
  { value: 36, label: 'Attack 1H (one-shot)' },
  { value: 37, label: 'Attack 2H Tight (one-shot)' },
  { value: 38, label: 'Attack 2H Loose (one-shot)' },
  { value: 39, label: 'Parry Unarmed (one-shot)' },
  { value: 43, label: 'Parry Shield (one-shot)' },
  { value: 44, label: 'Ready Unarmed (one-shot)' },
  { value: 45, label: 'Ready 1H (one-shot)' },
  { value: 48, label: 'Ready Bow (one-shot)' },
  { value: 50, label: 'Spell Precast (one-shot)' },
  { value: 51, label: 'Spell Cast (one-shot)' },
  { value: 53, label: 'Battle Roar (one-shot)' },
  { value: 54, label: 'Special Attack 1H (one-shot)' },
  { value: 60, label: 'Kick (one-shot)' },
  { value: 61, label: 'Attack Thrown (one-shot)' },
  { value: 64, label: 'Stun (state)' },
  { value: 65, label: 'Dead (state)' },
  { value: 66, label: 'Salute (one-shot)' },
  { value: 68, label: 'Kneel (state)' },
  { value: 69, label: 'Use Standing (state)' },
  { value: 70, label: 'Wave, No Sheathe (one-shot)' },
  { value: 71, label: 'Cheer, No Sheathe (one-shot)' },
  { value: 92, label: 'Eat, No Sheathe (one-shot)' },
  { value: 93, label: 'Stun, No Sheathe (state)' },
  { value: 94, label: 'Dance (one-shot)' },
  { value: 113, label: 'Salute, No Sheathe (one-shot)' },
  { value: 133, label: 'Use Standing, No Sheathe (state)' },
  { value: 153, label: 'Laugh, No Sheathe (one-shot)' },
  { value: 173, label: 'Work (state)' },
  { value: 193, label: 'Spell Precast (state)' },
  { value: 213, label: 'Ready Rifle (one-shot)' },
  { value: 214, label: 'Ready Rifle (state)' },
  { value: 233, label: 'Work Mining (state)' },
  { value: 234, label: 'Work Chopwood (state)' },
  { value: 253, label: 'Applaud (state)' },
  { value: 254, label: 'Liftoff (one-shot)' },
  { value: 273, label: 'Yes (one-shot)' },
  { value: 274, label: 'No (one-shot)' },
  { value: 275, label: 'Train (one-shot)' },
  { value: 293, label: 'Land (one-shot)' },
  { value: 313, label: 'At Ease (state)' },
  { value: 333, label: 'Ready 1H (state)' },
  { value: 353, label: 'Spell Kneel Start (state)' },
  { value: 373, label: 'Submerged (state)' },
  { value: 374, label: 'Submerge (one-shot)' },
  { value: 375, label: 'Ready 2H (state)' },
  { value: 376, label: 'Ready Bow (state)' },
  { value: 377, label: 'Mount Special (one-shot)' },
  { value: 378, label: 'Talk (state)' },
  { value: 379, label: 'Fishing (state)' },
  { value: 380, label: 'Fishing (one-shot)' },
  { value: 381, label: 'Loot (one-shot)' },
  { value: 382, label: 'Whirlwind (state)' },
  { value: 383, label: 'Drowned (state)' },
  { value: 384, label: 'Hold Bow (state)' },
  { value: 385, label: 'Hold Rifle (state)' },
  { value: 386, label: 'Hold Thrown (state)' },
  { value: 387, label: 'Drown (one-shot)' },
  { value: 388, label: 'Stomp (one-shot)' },
  { value: 389, label: 'Attack Off-hand (one-shot)' },
  { value: 390, label: 'Attack Off-hand Pierce (one-shot)' },
  { value: 391, label: 'Roar (state)' },
  { value: 392, label: 'Laugh (state)' },
  { value: 393, label: 'Creature Special (one-shot)' },
  { value: 394, label: 'Jump, Land and Run (one-shot)' },
  { value: 395, label: 'Jump, End (one-shot)' },
  { value: 396, label: 'Talk, No Sheathe (one-shot)' },
  { value: 397, label: 'Point, No Sheathe (one-shot)' },
  { value: 398, label: 'Cannibalize (state)' },
  { value: 399, label: 'Jump, Start (one-shot)' },
  { value: 400, label: 'Dance Special (state)' },
  { value: 401, label: 'Dance Special (one-shot)' },
  { value: 402, label: 'Custom Spell 01 (one-shot)' },
  { value: 403, label: 'Custom Spell 02 (one-shot)' },
  { value: 404, label: 'Custom Spell 03 (one-shot)' },
  { value: 405, label: 'Custom Spell 04 (one-shot)' },
  { value: 406, label: 'Custom Spell 05 (one-shot)' },
  { value: 407, label: 'Custom Spell 06 (one-shot)' },
  { value: 408, label: 'Custom Spell 07 (one-shot)' },
  { value: 409, label: 'Custom Spell 08 (one-shot)' },
  { value: 410, label: 'Custom Spell 09 (one-shot)' },
  { value: 411, label: 'Custom Spell 10 (one-shot)' },
  { value: 412, label: 'Exclaim (state)' },
  { value: 413, label: 'Dance, Custom (state)' },
  { value: 415, label: 'Sit in Chair, Medium (state)' },
  { value: 416, label: 'Custom Spell 01 (state)' },
  { value: 417, label: 'Custom Spell 02 (state)' },
  { value: 418, label: 'Eat (state)' },
  { value: 419, label: 'Custom Spell 04 (state)' },
  { value: 420, label: 'Custom Spell 03 (state)' },
  { value: 421, label: 'Custom Spell 05 (state)' },
  { value: 422, label: 'Spell Effect Hold (state)' },
  { value: 423, label: 'Eat, No Sheathe (state)' },
  { value: 424, label: 'Mount (state)' },
  { value: 425, label: 'Ready 2H Loose (state)' },
  { value: 426, label: 'Sit in Chair, High (state)' },
  { value: 427, label: 'Fall (state)' },
  { value: 428, label: 'Loot (state)' },
  { value: 429, label: 'Submerged, New (state)' },
  { value: 430, label: 'Cower (one-shot)' },
  { value: 431, label: 'Cower (state)' },
  { value: 432, label: 'Use Standing (one-shot)' },
  { value: 433, label: 'Stealth Stand (state)' },
  { value: 434, label: 'Omni-cast Ghoul (one-shot)' },
  { value: 435, label: 'Attack Bow (one-shot)' },
  { value: 436, label: 'Attack Rifle (one-shot)' },
  { value: 437, label: 'Swim Idle (state)' },
  { value: 438, label: 'Attack Unarmed (state)' },
  { value: 439, label: 'Spell Cast With Sound (one-shot)' },
  { value: 440, label: 'Dodge (one-shot)' },
  { value: 441, label: 'Parry 1H (one-shot)' },
  { value: 442, label: 'Parry 2H (one-shot)' },
  { value: 443, label: 'Parry 2H Loose (one-shot)' },
  { value: 444, label: 'Fly, Fall (state)' },
  { value: 445, label: 'Fly, Death (one-shot)' },
  { value: 446, label: 'Fly, Fall (falling) (state)' },
  { value: 447, label: 'Fly, Sit on Ground, Down (one-shot)' },
  { value: 448, label: 'Fly, Sit on Ground, Up (one-shot)' },
  { value: 449, label: 'Emerge (one-shot)' },
  { value: 450, label: 'Dragon Spit (one-shot)' },
  { value: 451, label: 'Special Unarmed (state)' },
  { value: 452, label: 'Fly, Grab (one-shot)' },
  { value: 453, label: 'Fly, Grab Closed (state)' },
  { value: 454, label: 'Fly, Grab Thrown (one-shot)' },
  { value: 455, label: 'Fly, Sit on Ground (state)' },
  { value: 456, label: 'Walk Backwards (state)' },
  { value: 457, label: 'Fly, Talk (one-shot)' },
  { value: 458, label: 'Fly, Attack 1H (one-shot)' },
  { value: 459, label: 'Custom Spell 08 (state)' },
  { value: 460, label: 'Fly, Dragon Spit (one-shot)' },
  { value: 461, label: 'Sit in Chair, Low (state)' },
  { value: 462, label: 'Stun (one-shot)' },
  { value: 463, label: 'Spell Cast, Omni-directional (one-shot)' },
  { value: 465, label: 'Ready Thrown (state)' },
  { value: 466, label: 'Work Chopwood (one-shot)' },
  { value: 467, label: 'Work Mining (one-shot)' },
  { value: 468, label: 'Spell Channel, Omni-directional (state)' },
  { value: 469, label: 'Spell Channel, Directed (state)' },
  { value: 470, label: 'Stand State None' },
  { value: 471, label: 'Ready Joust (state)' },
  { value: 473, label: 'Strangulate (state)' },
  { value: 474, label: 'Ready Spell, Omni-directional (state)' },
  { value: 475, label: 'Hold Joust (state)' },
  { value: 476, label: 'Cry Jaina (one-shot)' },
];
