// @ts-nocheck
// From @wowserhq/format 0.28.0 (MIT, Wowser Contributors); see ../../LICENSE.
var MAP_OBJ_FLAG;
(function (MAP_OBJ_FLAG) {
    MAP_OBJ_FLAG[MAP_OBJ_FLAG["FLAG_CVERTS_TRANS_ATTENUATED"] = 1] = "FLAG_CVERTS_TRANS_ATTENUATED";
    MAP_OBJ_FLAG[MAP_OBJ_FLAG["FLAG_UNIFIED_SHADING"] = 2] = "FLAG_UNIFIED_SHADING";
    MAP_OBJ_FLAG[MAP_OBJ_FLAG["FLAG_CVERTS_FIXED"] = 8] = "FLAG_CVERTS_FIXED";
})(MAP_OBJ_FLAG || (MAP_OBJ_FLAG = {}));
var MAP_OBJ_GROUP_FLAG;
(function (MAP_OBJ_GROUP_FLAG) {
    MAP_OBJ_GROUP_FLAG[MAP_OBJ_GROUP_FLAG["FLAG_CVERTS"] = 4] = "FLAG_CVERTS";
    MAP_OBJ_GROUP_FLAG[MAP_OBJ_GROUP_FLAG["FLAG_EXTERIOR"] = 8] = "FLAG_EXTERIOR";
    MAP_OBJ_GROUP_FLAG[MAP_OBJ_GROUP_FLAG["FLAG_EXTERIOR_LIT"] = 64] = "FLAG_EXTERIOR_LIT";
    MAP_OBJ_GROUP_FLAG[MAP_OBJ_GROUP_FLAG["FLAG_INTERIOR"] = 8192] = "FLAG_INTERIOR";
})(MAP_OBJ_GROUP_FLAG || (MAP_OBJ_GROUP_FLAG = {}));
var MAP_OBJ_MATERIAL_FLAG;
(function (MAP_OBJ_MATERIAL_FLAG) {
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_UNLIT"] = 1] = "FLAG_UNLIT";
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_UNFOGGED"] = 2] = "FLAG_UNFOGGED";
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_UNCULLED"] = 4] = "FLAG_UNCULLED";
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_EXTLIGHT"] = 8] = "FLAG_EXTLIGHT";
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_SIDN"] = 16] = "FLAG_SIDN";
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_WINDOW"] = 32] = "FLAG_WINDOW";
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_CLAMP_S"] = 64] = "FLAG_CLAMP_S";
    MAP_OBJ_MATERIAL_FLAG[MAP_OBJ_MATERIAL_FLAG["FLAG_CLAMP_T"] = 128] = "FLAG_CLAMP_T";
})(MAP_OBJ_MATERIAL_FLAG || (MAP_OBJ_MATERIAL_FLAG = {}));
var MAP_OBJ_FRAGMENT_SHADER;
(function (MAP_OBJ_FRAGMENT_SHADER) {
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_DIFFUSE"] = 0] = "FRAGMENT_DIFFUSE";
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_SPECULAR"] = 1] = "FRAGMENT_SPECULAR";
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_METAL"] = 2] = "FRAGMENT_METAL";
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_ENV"] = 3] = "FRAGMENT_ENV";
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_OPAQUE"] = 4] = "FRAGMENT_OPAQUE";
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_ENV_METAL"] = 5] = "FRAGMENT_ENV_METAL";
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_COMPOSITE"] = 6] = "FRAGMENT_COMPOSITE";
    MAP_OBJ_FRAGMENT_SHADER[MAP_OBJ_FRAGMENT_SHADER["FRAGMENT_UNKNOWN"] = 7] = "FRAGMENT_UNKNOWN";
})(MAP_OBJ_FRAGMENT_SHADER || (MAP_OBJ_FRAGMENT_SHADER = {}));
var MAP_OBJ_VERTEX_SHADER;
(function (MAP_OBJ_VERTEX_SHADER) {
    MAP_OBJ_VERTEX_SHADER[MAP_OBJ_VERTEX_SHADER["VERTEX_DIFFUSE_T1"] = 0] = "VERTEX_DIFFUSE_T1";
    MAP_OBJ_VERTEX_SHADER[MAP_OBJ_VERTEX_SHADER["VERTEX_DIFFUSE_T1_REFL"] = 1] = "VERTEX_DIFFUSE_T1_REFL";
    MAP_OBJ_VERTEX_SHADER[MAP_OBJ_VERTEX_SHADER["VERTEX_DIFFUSE_COMP"] = 2] = "VERTEX_DIFFUSE_COMP";
    MAP_OBJ_VERTEX_SHADER[MAP_OBJ_VERTEX_SHADER["VERTEX_SPECULAR_T1"] = 3] = "VERTEX_SPECULAR_T1";
    MAP_OBJ_VERTEX_SHADER[MAP_OBJ_VERTEX_SHADER["VERTEX_UNKNOWN"] = 4] = "VERTEX_UNKNOWN";
})(MAP_OBJ_VERTEX_SHADER || (MAP_OBJ_VERTEX_SHADER = {}));
const MAP_OBJ_SHADER = [
    // Shader 0
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_DIFFUSE,
    },
    // Shader 1
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_SPECULAR_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_SPECULAR,
    },
    // Shader 2
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_SPECULAR_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_METAL,
    },
    // Shader 3
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1_REFL,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_ENV,
    },
    // Shader 4
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_OPAQUE,
    },
    // Shader 5
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1_REFL,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_ENV_METAL,
    },
    // Shader 6
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_COMP,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_COMPOSITE,
    },
];
export { MAP_OBJ_FLAG, MAP_OBJ_GROUP_FLAG, MAP_OBJ_MATERIAL_FLAG, MAP_OBJ_FRAGMENT_SHADER, MAP_OBJ_VERTEX_SHADER, MAP_OBJ_SHADER, };
