// From @wowserhq/format 0.28.0 (MIT, Wowser Contributors); see ../../LICENSE.
// Written back as the TypeScript enums the package compiled them from.

enum MAP_OBJ_FLAG {
  FLAG_CVERTS_TRANS_ATTENUATED = 1,
  FLAG_UNIFIED_SHADING = 2,
  FLAG_CVERTS_FIXED = 8,
}

enum MAP_OBJ_GROUP_FLAG {
  FLAG_CVERTS = 4,
  FLAG_EXTERIOR = 8,
  FLAG_EXTERIOR_LIT = 64,
  FLAG_INTERIOR = 8192,
}

enum MAP_OBJ_MATERIAL_FLAG {
  FLAG_UNLIT = 1,
  FLAG_UNFOGGED = 2,
  FLAG_UNCULLED = 4,
  FLAG_EXTLIGHT = 8,
  FLAG_SIDN = 16,
  FLAG_WINDOW = 32,
  FLAG_CLAMP_S = 64,
  FLAG_CLAMP_T = 128,
}

enum MAP_OBJ_FRAGMENT_SHADER {
  FRAGMENT_DIFFUSE = 0,
  FRAGMENT_SPECULAR = 1,
  FRAGMENT_METAL = 2,
  FRAGMENT_ENV = 3,
  FRAGMENT_OPAQUE = 4,
  FRAGMENT_ENV_METAL = 5,
  FRAGMENT_COMPOSITE = 6,
  FRAGMENT_UNKNOWN = 7,
}

enum MAP_OBJ_VERTEX_SHADER {
  VERTEX_DIFFUSE_T1 = 0,
  VERTEX_DIFFUSE_T1_REFL = 1,
  VERTEX_DIFFUSE_COMP = 2,
  VERTEX_SPECULAR_T1 = 3,
  VERTEX_UNKNOWN = 4,
}
const MAP_OBJ_SHADER = [
    // Shader 0
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_DIFFUSE,
    },
    // Shader 1
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_SPECULAR_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_SPECULAR,
    },
    // Shader 2
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_SPECULAR_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_METAL,
    },
    // Shader 3
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1_REFL,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_ENV,
    },
    // Shader 4
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_OPAQUE,
    },
    // Shader 5
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_T1_REFL,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_ENV_METAL,
    },
    // Shader 6
    {
        vertexShader: MAP_OBJ_VERTEX_SHADER.VERTEX_DIFFUSE_COMP,
        fragmentShader: MAP_OBJ_FRAGMENT_SHADER.FRAGMENT_COMPOSITE,
    },
];
export { MAP_OBJ_FLAG, MAP_OBJ_GROUP_FLAG, MAP_OBJ_MATERIAL_FLAG, MAP_OBJ_FRAGMENT_SHADER, MAP_OBJ_VERTEX_SHADER, MAP_OBJ_SHADER, };
