/**
 * The 3.3.5a reputation factions a quest can reward or require: the `Faction.dbc` rows with a
 * reputation index. The fork's `faction_dbc` world table (`data/coa-world/.../faction_dbc.sql` in
 * `E:\Repositories\azerothcore-wotlk-coa`) ships empty, so the IDs and names are the stock 3.3.5a
 * client's. A custom faction the fork adds is not listed; the dropdown keeps it as `#ID`.
 */
const FACTIONS: ReadonlyArray<readonly [number, string]> = [
  [21, 'Booty Bay'],
  [47, 'Ironforge'],
  [54, 'Gnomeregan Exiles'],
  [59, 'Thorium Brotherhood'],
  [68, 'Undercity'],
  [69, 'Darnassus'],
  [70, 'Syndicate'],
  [72, 'Stormwind'],
  [76, 'Orgrimmar'],
  [81, 'Thunder Bluff'],
  [87, 'Bloodsail Buccaneers'],
  [92, 'Gelkis Clan Centaur'],
  [93, 'Magram Clan Centaur'],
  [270, 'Zandalar Tribe'],
  [349, 'Ravenholdt'],
  [369, 'Gadgetzan'],
  [470, 'Ratchet'],
  [509, 'The League of Arathor'],
  [510, 'The Defilers'],
  [529, 'Argent Dawn'],
  [530, 'Darkspear Trolls'],
  [576, 'Timbermaw Hold'],
  [577, 'Everlook'],
  [589, 'Wintersaber Trainers'],
  [609, 'Cenarion Circle'],
  [729, 'Frostwolf Clan'],
  [730, 'Stormpike Guard'],
  [749, 'Hydraxian Waterlords'],
  [809, "Shen'dralar"],
  [889, 'Warsong Outriders'],
  [890, 'Silverwing Sentinels'],
  [909, 'Darkmoon Faire'],
  [910, 'Brood of Nozdormu'],
  [911, 'Silvermoon City'],
  [922, 'Tranquillien'],
  [930, 'Exodar'],
  [932, 'The Aldor'],
  [933, 'The Consortium'],
  [934, 'The Scryers'],
  [935, "The Sha'tar"],
  [941, "The Mag'har"],
  [942, 'Cenarion Expedition'],
  [946, 'Honor Hold'],
  [947, 'Thrallmar'],
  [967, 'The Violet Eye'],
  [970, 'Sporeggar'],
  [978, 'Kurenai'],
  [989, 'Keepers of Time'],
  [990, 'The Scale of the Sands'],
  [1011, 'Lower City'],
  [1012, 'Ashtongue Deathsworn'],
  [1015, 'Netherwing'],
  [1031, "Sha'tari Skyguard"],
  [1037, 'Alliance Vanguard'],
  [1038, "Ogri'la"],
  [1050, 'Valiance Expedition'],
  [1052, 'Horde Expedition'],
  [1064, 'The Taunka'],
  [1067, 'The Hand of Vengeance'],
  [1068, "Explorers' League"],
  [1073, "The Kalu'ak"],
  [1077, 'Shattered Sun Offensive'],
  [1085, 'Warsong Offensive'],
  [1090, 'Kirin Tor'],
  [1091, 'The Wyrmrest Accord'],
  [1094, 'The Silver Covenant'],
  [1098, 'Knights of the Ebon Blade'],
  [1104, 'Frenzyheart Tribe'],
  [1105, 'The Oracles'],
  [1106, 'Argent Crusade'],
  [1119, 'The Sons of Hodir'],
  [1124, 'The Sunreavers'],
  [1126, 'The Frostborn'],
  [1156, 'The Ashen Verdict'],
];

export const REPUTATION_FACTIONS: readonly { id: number; name: string }[] = FACTIONS.map(([id, name]) => ({ id, name })).sort(
  (a, b) => a.name.localeCompare(b.name),
);

const byId = new Map(FACTIONS);

export function factionName(id: number): string | undefined {
  return byId.get(id);
}
